-- Widgets table seeds here (Example)
INSERT INTO listings  (user_id, title, description, price, thumbnail_photo, year, make, model) VALUES (1, 'SN10', 'Great Rocket that will get you to space and back! Slight hiccups on landing. Fixer upper that could use a little tlc.', 5000, 'https://c.ndtvimg.com/2021-03/767bnudo_spacex-starship-explodes-reuters_625x300_04_March_21.jpg', 2019, 'Tesla', 'SN10');
INSERT INTO listings (user_id, title, description, price, thumbnail_photo, year, make, model) VALUES (2, 'Sea Duck', "Lightly used seaplane, some bullet holes, some claw marks. If it's got wings, you can fly it!", 27000, 'https://talespin.fandom.com/wiki/Sea_Duck?file=Seaduck03.jpg', 1947, 'Conwing', 'L-16');
INSERT INTO listings (user_id, title, description, price, thumbnail_photo, year, make, model) VALUES (3, 'Gipsy Moth', '1920s British two-seat touring and training aircraft that has broken a number of record-breaking solo flights around the world', 8000, 'https://www.baesystems.com/en/download-en/heritageimage/webImage/20170730112548/1434600083386.jpg', 1925, 'de Havilland DH.60 Moth', 'Gipsy Moth');
INSERT INTO listings (user_id, title, description, price, thumbnail_photo, year, make, model) VALUES (4, 'Millenium Falcon', 'The Falcon is the ship that did the Kessel Run in less than 12 parsecs.', 300000, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq1_MyrU366LGBbud4ALXnTJAW2WYb3MzR6w&usqp=CAU', 1977, 'CEC', 'YT-1300');
INSERT INTO listings (user_id, title, description, price, thumbnail_photo, year, make, model) VALUES (5, 'F-4 Phantom', 'Do you feel the need...the need for speed? This plane will site you back in your seat!', 250000, 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/4359850-1527788497.jpg?crop=1xw:1xh;center,top&resize=768:*', 1986, 'Lockhead Martin', 'F-14');
INSERT INTO listings (user_id, title, description, price, thumbnail_photo, year, make, model) VALUES (6, 'Kukuruznik', 'Многие нацисты в ужасе бежали от ночных ведьм! Вы тоже могли бы стать одним из них!', 4000, 'https://www.militaryfactory.com/aircraft/imgs/polikarpov-po2-mule.jpg', 1927, 'Polikarpov', 'Po-2');
INSERT INTO listings (user_id, title, description, price, thumbnail_photo, year, make, model) VALUES (7, 'Snakes on a Plane', 'I have had it with these ************* snakes on this ************* plane!!!!',15000, 'https://jundroo.blob.core.windows.net/simpleplanes/GameData/aircraft/61/BT5hFm-UserView-1.png', 2006, 'Boeing', '747-400');
INSERT INTO listings (user_id, title, description, price, thumbnail_photo, year, make, model) VALUES (8, 'Airbus A320', 'Plane has some light to moderate water damage. Will need to be dragged out of the Hudson River by buyer.', 20000, 'https://upload.wikimedia.org/wikipedia/commons/8/8f/US_Airways_Flight_1549_%28N106US%29_after_crashing_into_the_Hudson_River_%28crop_2%29.jpg', 2010, 'Boeing', 'A320-214');
